# Generated by Django 5.1.7 on 2025-03-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_type", models.CharField(max_length=50)),
                ("number_plate", models.CharField(max_length=20, unique=True)),
                ("owner_name", models.CharField(max_length=100)),
                ("phone_no", models.CharField(max_length=15)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("fine_status", models.CharField(default="Pending", max_length=20)),
            ],
        ),
    ]
