# Generated by Django 5.1.7 on 2025-03-19 22:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fines", "0002_vehicleowner"),
    ]

    operations = [
        migrations.AddField(
            model_name="fine",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
