# Generated by Django 5.1.7 on 2025-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fines", "0003_fine_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleowner",
            name="fine_status",
            field=models.CharField(default="Unpaid", max_length=20),
        ),
    ]
